server {
  listen 80;
  server_name localhost;
  client_max_body_size 50m;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://policymind_ai:8080/;
    proxy_http_version 1.1;
    add_header Cache-Control "no-store, no-cache, max-age=0, must-revalidate" always;
    add_header Pragma "no-cache" always;
    add_header Expires "0" always;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Authorization $http_authorization;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
