services:
  postgres:
    env_file:
      - .env.production
    ports: []

  redis:
    ports: []

  policymind:
    image: policymind-backend:ec2
    env_file:
      - .env.production
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/policymind-ai-80ed72ade163.json
    volumes:
      - ./secrets/policymind-ai-80ed72ade163.json:/app/secrets/policymind-ai-80ed72ade163.json:ro

  frontend:
    image: policymind-frontend:ec2
