spring:
  sql:
    init:
      mode: never
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true
        same-site: lax
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
